### ISSUE TITLE
Usage with multiprocessing.Pool

### ISSUE THREAD

**Issue by FlorianWilhelm** [dask/hdfs3#100]
I want to read in parallel from hdfs using following dummy code that is actually reading but doing nothing so just for demonstration purposes:
```python
import sys
import time
import random
import logging
from multiprocessing import Pool

from hdfs3 import HDFileSystem
from hdfs3.compatibility import ConnectionError

_logger = logging.getLogger(__name__)


def get_hdfs_client(host, port):
    """Creates a HDFS client

    Args:
        host (str): host name of the HDFS servers
        port (int): port of the HDFS servers

    Returns:
        hdfs client object from the hdfs3 library
    """
    try:
        pars = {"hadoop.security.authentication": "kerberos"}
        hdfs_client = HDFileSystem(host=host, port=port, pars=pars)
    except ConnectionError:
        _logger.exception("HDFSConnectionError")
        _logger.error("Have you authenticated with `kinit` yet?")
        sys.exit(1)
    return hdfs_client


class MultiReader(object):
    def __init__(self, host, port, process_count):
        self.pool = Pool(processes=process_count, initializer=self._setup,
                         initargs=(host, port, process_count))

    def read_profiles(self, file_paths):
        self.pool.map(_multi_read, file_paths)

    def close_pool(self):
        self.pool.close()
        self.pool.join()

    @classmethod
    def _setup(cls, host, port, process_count):
        cls.client = get_hdfs_client(host, port)

    @classmethod
    def _read_concurrent(cls, file_path):
        with cls.client.open(file_path) as fh:
            for row in fh:
                pass


def _multi_read(file_path):
    MultiReader._read_concurrent(file_path)


if __name__ == '__main__':
    host = 'my_host'
    port = 8020
    file_path = '/user/my_user/tmp'
    
    hdfs = get_hdfs_client(host, port)
    file_paths = [f for f in hdfs.walk(file_path) if hdfs.info(f)['kind'] == 'file']
    hdfs.disconnect()
    del hdfs
    time.sleep(5)
    
    # Using this line and commenting the block above causes no error messages
    # file_paths = ['{}/{:0>6}_0'.format(file_path, i) for i in range(250)]

    multi_read = MultiReader(host, port, 10)
    multi_read.read_profiles(file_paths)
```
So when the main process somewhere has a hdfs client object generated I am seeing a lot of following errors but still it runs (is it okay to ignore those errors?):
```
2016-11-16 12:52:50.671476, p9902, th139871594358528, ERROR Failed to invoke RPC call "getFsStats" on server "XXXXXXXXXXXXXX:8020": 
RpcChannel.cpp: 393: HdfsRpcException: Failed to invoke RPC call "getFsStats" on server "XXXXXXXXXXXX:8020"
        @       Hdfs::Internal::RpcChannelImpl::invokeInternal(boost::shared_ptr<Hdfs::Internal::RpcRemoteCall>)
        @       Hdfs::Internal::RpcChannelImpl::invoke(Hdfs::Internal::RpcCall const&)
        @       Hdfs::Internal::NamenodeImpl::invoke(Hdfs::Internal::RpcCall const&)
        @       Hdfs::Internal::NamenodeImpl::getFsStats()
        @       Hdfs::Internal::NamenodeProxy::getFsStats()
        @       Hdfs::Internal::FileSystemImpl::getFsStats()
        @       Hdfs::Internal::FileSystemImpl::connect()
        @       Hdfs::FileSystem::connect(char const*, char const*, char const*)
        @       hdfsBuilderConnect
        @       ffi_call_unix64
        @       ffi_call
        @       _ctypes_callproc
        @       PyCFuncPtr_call
        @       PyObject_Call
        @       PyEval_EvalFrameEx
        @       PyEval_EvalFrameEx
        @       _PyEval_EvalCodeWithName
        @       PyEval_EvalCodeEx
        @       function_call
        @       PyObject_Call
        @       method_call
        @       PyObject_Call
        @       slot_tp_init
        @       type_call
        @       PyObject_Call
        @       PyEval_EvalFrameEx
        @       PyEval_EvalFrameEx
        @       _PyEval_EvalCodeWithName
        @       PyEval_EvalCodeEx
        @       function_call
        @       PyObject_Call
....
```

I know that I should not have an hdfs client object when forking but that is why I am disconnecting and even deleting the object. Is this a bug or an intended behavior? Is there no way I can use hdfs client objects in the master process as well as in the child processes? Is the only workaround now that I fork a special process in order to execute the `walk` command?

**Comment by martindurant** [comment]
Sorry for not replying sooner. Disconnecting the python side of the hdfs3 object as you do still leaves the shared library, libhdfs3, in memory together with any initialization state, which will be distributed upon fork. The problem probably stems from OS pipes. In any case, you can work around this by having pre-existing worker processes up and running before starting hdfs interaction in the main one, and passing tasks using Queues. I would instead suggest (because I'm biased) using dask-distributed to control workers.

So long as you are not writing simultaneously from different processes, it may well be that the errors can be ignored, but I am not sure.

**Comment by pitrou** [comment]
The clean approach to this is to use the `forkserver` method on Python 3: https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
Otherwise libhdfs3 (the underlying C library) will be confused if you fork a process after you start using it.

Note dask-distributed defaults to `forkserver` on Python 3.

**Comment by FlorianWilhelm** [comment]
Thanks @martindurant  and @pitrou, I tried the `forkserver` option in Python3 multiprocessing and got rid of the error messages. Will convert my code to dask in the future since it is a higher abstraction than the multiprocessing module.

**Comment by eromoe** [comment]
I still got error
```
Traceback (most recent call last):
  File "etl.py", line 418, in <module>
    cli()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "etl.py", line 238, in multi_transform_each
    mp.set_start_method('forkserver')
  File "/usr/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

My code:
```
@cli.command()
def multi_transform_each():

    mp.set_start_method('forkserver')

    hdfs = HdfsClient(host=HDFS_HOST, port=HDFS_PORT)

    with Pool(processes=4) as pool:
        pool.map(etl_order_items, [path for path in hdfs.glob('/arch/M/orderitems/2017/*.parquet')])

    with Pool(processes=4) as pool:
        pool.map(etl_stock_quantity_log, [path for path in hdfs.glob('/arch/M/stockquantitylogs/2017/*.parquet')])
```

**Comment by eromoe** [comment]
I move that to ` __main__` still error :
```
Traceback (most recent call last):
  File "etl.py", line 418, in <module>
    multiprocessing.set_start_method('forkserver')
  File "/usr/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

**Comment by martindurant** [comment]
The traceback indicated that that the problem is coming from your own code: `multiprocessing.set_start_method('forkserver')`

**Comment by eromoe** [comment]
I solved it by put below on top of this file . 
```
import multiprocessing

try:
    multiprocessing.set_start_method('forkserver')
except:
    pass
```

Some people move it to `__main__` to ensure it only execute once, but seems other libs would disturb .
Have to move on top and add try except.
