### ISSUE TITLE
`boost` version incompatibility

### ISSUE THREAD

**Issue by DGrady** [dask/hdfs3#66]
After installing `hdfs3` in a clean `conda` environment with these commands

```
conda create --name hdfs3test python=3
source activate hdfs3
conda install -c dask hdfs3
```

I get the following error after trying `import hdfs3` in the Python interpreter:

```
Traceback (most recent call last):                                                                                                                                                   
File "<stdin>", line 1, in <module>                                                                                                                                                
File "/work/analytics2/analytics/python/envs/hdfs3test/lib/python3.5/site-packages/hdfs3/__init__.py", line 1, in <module>                                                         
  from .core import HDFileSystem, HDFile                                                                                                                                           
File "/work/analytics2/analytics/python/envs/hdfs3test/lib/python3.5/site-packages/hdfs3/core.py", line 12, in <module>                                                            
  from .lib import _lib                                                                                                                                                            
File "/work/analytics2/analytics/python/envs/hdfs3test/lib/python3.5/site-packages/hdfs3/lib.py", line 11, in <module>                                                             
  _lib = ct.cdll.LoadLibrary('libhdfs3.so')                                                                                                                                        
File "/work/analytics2/analytics/python/envs/hdfs3test/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary                                                                 
  return self._dlltype(name)                                                                                                                                                       
File "/work/analytics2/analytics/python/envs/hdfs3test/lib/python3.5/ctypes/__init__.py", line 347, in __init__                                                                    
  self._handle = _dlopen(self._name, mode)                                                                                                                                         
OSError: libboost_thread.so.1.57.0: cannot open shared object file: No such file or directory
```

Downgrading the installed version of `boost` with `conda install boost=1.57` seems to fix the issue.

**Comment by koverholt** [comment]
Thanks for reporting this! I'm looking into this now.

**Comment by hsaputra** [comment]
+1 to get this one fixed

**Comment by hsaputra** [comment]
Thx @DGrady for the workaround tip

**Comment by koverholt** [comment]
I've rebuilt `libhdfs3` with `boost` 1.60 and reuploaded to the `dask` channel on anaconda.org. I also pinned `boost` 1.60 to the `libhdfs3` conda package, so this won't happen again if `boost` is updated in Anaconda in the future.

Things should now work with the usual:

```
conda install hdfs3 -c dask
```

Thanks again @DGrady and @hsaputra for reporting! Please reopen if you have any issues.

**Comment by DGrady** [comment]
Thanks for the quick fix!
